.TH SLYTHER 6 "July 2019" "Dick Balaska" "Version 2.0.0" \" -*- nroff -*-
.\" (C) Copyright 2019 Dick Balaska <dick@buckosoft.com>,
.\"
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
slyther \- Eat and grow your snake.
.SH SYNOPSIS
.B slyther
.RI [ options ]
.br
.B slyther-server
.RI [ options ]
.SH DESCRIPTION
This manual page documents briefly the
.B slyther
and
.B slyther-server
commands.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics,
.\" respectively.
\fBslyther\fP is a game where you grow your snake by eating. 
Protect your face from other snakes or you will turn into food for them.
.SH OPTIONS
.TP
.B \-d
Enable debug to stdout
.TP
.B \-v
Show version of program and exit.
.TP
.B \-g <dir>
Set the gameFolder directory, where user data is stored.
.br
The default for debian systems is 
.B $HOME/.config/slyther
.SH SEE ALSO
Source code at github
.UR https://github.com/dickbalaska/slyther
.UE
